### ISSUE TITLE
Windows 10 with R2018b and MinGW64 Compiler (C++)

### ISSUE THREAD

**Issue by Carlbouakl** [plstcharles/libelas#1]
So since R2018b doesn't support 2008 C++ I had to compile with MinGW64. The issue is that I am getting the following error msg:

Error using mex
g++: error: \-fexceptions: No such file or directory

Error in make (line 25)
mex('elasMex.cpp','../src/elas.cpp','../src/descriptor.cpp', '../src/filter.cpp', ...

Naturally, I changed CXXFLAGS to COMPFLAGS, and obtained the following:
>> make
Building wrappers ...
Building with 'MinGW64 Compiler (C++)'.
Error using mex
C:\Users\Carl\Desktop\matlab\elasMex.cpp: In function 'void mexFunction(int, mxArray**, int, const mxArray**)':
C:\Users\Carl\Desktop\matlab\elasMex.cpp:90:50: error: cannot convert 'const mwSize* {aka const long long unsigned int*}' to 'const
int32_t* {aka const int*}' in initialization
   const int32_t *I_dims = mxGetDimensions(prhs[0]);
                                                  ^
C:\Users\Carl\Desktop\matlab\elasMex.cpp:98:68: error: cannot convert 'int32_t* {aka int*}' to 'const mwSize* {aka const long long
unsigned int*}' for argument '2' to 'mxArray* mxCreateNumericArray_730(mwSize, const mwSize*, mxClassID, mxComplexity)'
   plhs[0]     = mxCreateNumericArray(2,D_dims,mxSINGLE_CLASS,mxREAL);
                                                                    ^
C:\Users\Carl\Desktop\matlab\elasMex.cpp:100:68: error: cannot convert 'int32_t* {aka int*}' to 'const mwSize* {aka const long long
unsigned int*}' for argument '2' to 'mxArray* mxCreateNumericArray_730(mwSize, const mwSize*, mxClassID, mxComplexity)'
   plhs[1]     = mxCreateNumericArray(2,D_dims,mxSINGLE_CLASS,mxREAL);
                                                                    ^

Error in make (line 25)
mex('elasMex.cpp','../src/elas.cpp','../src/descriptor.cpp', '../src/filter.cpp', ...
 

Any help?

**Comment by plstcharles** [comment]
It would be pretty hard for me to reproduce this issue right now, but from the error log, it seems like a 32bit/64bit compilation issue. Modifying the code to handle 64 bit values (via mwSize instead of int32_t) or compiling it with a 32 bit toolchain might fix your issue.

**Comment by Carlbouakl** [comment]
Used 32 bit MATLAB and it worked perfectly
Thanks a lot
